apiVersion: v1
kind: Service
metadata:
  name: pdf-reader-client-service
spec:
  selector:
    app: pdf-reader-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: LoadBalancer
