apiVersion: v1
kind: Service
metadata:
  name: pdf-reader-admin-service
spec:
  selector:
    app: pdf-reader-admin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer
